### ISSUE TITLE
Update hypothesis and Pytorch version

### ISSUE THREAD

**Issue by Dref360** [janfreyberg/torch-hypothesis#1]
Hello!

I was wondering if we could update hypothesis and pytorch versions? They are pretty old and it forces us (https://github.com/ElementAI/baal/) to install this library with '--no-deps'

Thanks!

**Comment by janfreyberg** [comment]
Yes, will do, apologies :)

**Comment by Dref360** [comment]
I submitted a PR #2. I hope that it is helpful!
